sudo: required

language: python

python:
  - '2.7'
  - '3.6'

install:
  - pip install -r requirements.txt

script: pytest --cov=hello_app tests && coveralls

jobs:
  include:
    - stage: lint
      script: flake8 hello_app tests
    - stage: deploy
      script: scripts/deploy.sh
      if: branch IN (master, develop) AND type = push
