sudo: required

language: python

python:
  - '2.7'
  - '3.6'

install:
  - pip install -r requirements.txt

script: pytest --cov=hello_app tests/

jobs:
  include:
    - stage: deploy
      python: 2.7
      script: scripts/deploy.sh
      if: branch IN (master, develop) AND type = push

after_success:
  - coveralls
