sudo: required

language: python

python:
  - '2.7'

script: python hello.py

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    all_branches: true
    $TRAVIS_BRANCH =~ ^master|develop$
