sudo: required

language: python

python:
  - '2.7'
  - '3.6'

install:
  - scripts/install.sh travis

script: pytest --cov=hello_app tests && coveralls

jobs:
  include:
    - stage: lint
      script: shellcheck scripts/*.sh && flake8 hello_app tests

    - stage: deploy to production
      script: scripts/deploy.sh 8200 stacks-production
      if: branch IN (master) AND type = push

    - stage: deploy to staging
      script: scripts/deploy.sh 8210 stacks-staging
      if: branch IN (develop) AND type = push
