sudo: required

language: python

python:
  - '2.7'

install:
  - pip install -r requirements.txt

script: pytest

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^master|develop$
