sudo: required

language: python

python:
  - '2.7'
  - '3.6'

install:
  - pip install -r requirements.txt

stages:
  - test
  - name: deploy
    if: branch IN (master, develop)

jobs:
  include:
    - script: pytest --cov=hello_app tests/ && coveralls
    - stage: deploy
      python: 2.7
      script: scripts/deploy.sh
